### ISSUE TITLE
Critical bug on live on login

### ISSUE THREAD

**Issue by sasfeld** [neeedo/neeedo-webapp#2]
On login of some users, the app crashes completely:

2015-07-20T19:43:36.212199+00:00 app[web.1]: { url: 'https://api.neeedo.com/users/mail/peter.gerhard90@gmail.com',
2015-07-20T19:43:36.212202+00:00 app[web.1]:   port: null,
2015-07-20T19:43:36.212201+00:00 app[web.1]:   hostname: 'api.neeedo.com',
2015-07-20T19:43:36.212204+00:00 app[web.1]:   path: '/users/mail/peter.gerhard90@gmail.com',
2015-07-20T19:43:36.212205+00:00 app[web.1]:   method: 'GET',
2015-07-20T19:43:36.212208+00:00 app[web.1]:   headers: { Authorization: 'Basic [REMOVED] } }
2015-07-20T19:43:36.212207+00:00 app[web.1]:   rejectUnauthorized: false,
2015-07-20T19:43:36.698152+00:00 app[web.1]: Error while loading user's favorites: { response: undefined,
2015-07-20T19:43:36.711536+00:00 app[web.1]:     at Object.module.exports.loadUsersFavoriteOffers (/app/api/services/FavoritesService.js:57:7)
2015-07-20T19:43:36.698155+00:00 app[web.1]:   errorMessages: [ 'Your inputs were not valid.' ],
2015-07-20T19:43:36.711500+00:00 app[web.1]: /app/api/services/ApiClientService.js:151
2015-07-20T19:43:36.711515+00:00 app[web.1]:     at Object.bound [as logMessages](/app/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
2015-07-20T19:43:36.698157+00:00 app[web.1]:   validationMessages: [],
2015-07-20T19:43:36.711505+00:00 app[web.1]:     for (var i = 0; i < errorModel.getLogMessages().length; i++) {
2015-07-20T19:43:36.698158+00:00 app[web.1]:   originalParams: [],
2015-07-20T19:43:36.698160+00:00 app[web.1]:   logMessages: [ 'loadUsersFavoriteOffers:undefined is not a function' ] }
2015-07-20T19:43:36.711508+00:00 app[web.1]:                                    ^
2015-07-20T19:43:36.711560+00:00 app[web.1]:     at responseHandler.handle.errorHandler.newErrorWithData.methodPath (/app/node_modules/neeedo-api-nodejs-client/services/login.js:51:29)
2015-07-20T19:43:36.711513+00:00 app[web.1]:     at Object.module.exports.logMessages (/app/api/services/ApiClientService.js:151:36)
2015-07-20T19:43:36.711531+00:00 app[web.1]:     at onErrorCallback (/app/api/controllers/RegistrationController.js:6:24)
2015-07-20T19:43:36.711510+00:00 app[web.1]: TypeError: undefined is not a function
2015-07-20T19:43:36.711561+00:00 app[web.1]:     at IncomingMessage.<anonymous> (/app/node_modules/neeedo-api-nodejs-client/helpers/response-handler.js:22:9)
2015-07-20T19:43:36.711563+00:00 app[web.1]:     at IncomingMessage.emit (events.js:129:20)
2015-07-20T19:43:36.711566+00:00 app[web.1]:     at process._tickDomainCallback (node.js:381:11)
2015-07-20T19:43:36.711533+00:00 app[web.1]:     at /app/api/services/LoginService.js:32:13
2015-07-20T19:43:36.748489+00:00 app[web.1]: npm ERR! node v0.12.7
2015-07-20T19:43:36.694691+00:00 app[web.1]: Server sent response data {"user":{"id":"27315a76-c941-4652-a6a3-fda3758e5144","version":1,"name":"peter","email":"peter.gerhard90@gmail.com"}}
2015-07-20T19:43:36.711556+00:00 app[web.1]:     at Object.bound [as loadUsersFavoriteOffers](/app/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
2015-07-20T19:43:36.711564+00:00 app[web.1]:     at _stream_readable.js:908:16
2015-07-20T19:43:36.742427+00:00 app[web.1]: 

Research for the problem

**Comment by sasfeld** [comment]
I think, c57da6ab256942ef15c460162d3ebf235a650b05 solved the last webapp crash, but not the main reason for it (why is no error model given to the log message ?)

**Comment by sasfeld** [comment]
fixed by 5ece0a17351292fc1a3133a9463147984ae15971
